### ISSUE TITLE
Accessibility testing - Sim Daltonism

### ISSUE THREAD

**Issue by karenhodgkinson** [nep2ne/ecommerce-pattern-library#10]
It's a bit difficult to tell when buttons / links are in an active/hover state vs inactive (see screenshots - all are different types of colour blindness even though they look the same). It wasn't too bad, just increased difficulty of distinguishing between them. Great use of underlines to indicate nav link states!

<img width="250" alt="Screen Shot 2019-04-16 at 1 12 33 PM" src="https://user-images.githubusercontent.com/31959335/56230113-99c1ba00-6049-11e9-804b-62c1ded658d2.png">
<img width="273" alt="Screen Shot 2019-04-16 at 1 12 37 PM" src="https://user-images.githubusercontent.com/31959335/56230114-99c1ba00-6049-11e9-8007-76514465fc4c.png">
<img width="1029" alt="Screen Shot 2019-04-16 at 1 13 04 PM" src="https://user-images.githubusercontent.com/31959335/56230115-99c1ba00-6049-11e9-89f5-54131fad44ba.png">
<img width="1117" alt="Screen Shot 2019-04-16 at 1 13 14 PM" src="https://user-images.githubusercontent.com/31959335/56230116-99c1ba00-6049-11e9-96e8-cf147cca2e67.png">

**Comment by nep2ne** [comment]
Thanks! I'll look into that!
