### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by ixamxkamii** [nep2ne/ecommerce-pattern-library#4]
Everything works really well.
Only things I have to mention are:
- Privacy policy and terms of use link is hard to see
- Hover on bulk promo banner is pretty delayed
- On your bulk promo page, once clicking the checkbox for signing up to the newsletter, the entire page shifts
![Capture](https://user-images.githubusercontent.com/31733729/56224431-a0e2cb00-603d-11e9-857e-7e6798d94f4e.JPG)

**Comment by nep2ne** [comment]
Wow! No idea why it's doing that. :) I'll look into it. Thanks!
