### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by jako-ry** [nep2ne/ecommerce-pattern-library#5]
There are some minor issues like I can't see the focus on some areas so I can't tell what link I'm going to click with the keyboard (on the homepage for your product categories, the social icons in the footer, the search & cart icons)

& there are also areas where there are invisible links.

<img width="365" alt="Screen Shot 2019-04-16 at 11 47 53 AM" src="https://user-images.githubusercontent.com/31830914/56224354-7db81b80-603d-11e9-849e-9b41a9b79047.png">

**Comment by nep2ne** [comment]
Thanks! I'll look into that. :)
