### ISSUE TITLE
Desktop Mozilla Firefox

### ISSUE THREAD

**Issue by patricia568** [nep2ne/ecommerce-pattern-library#7]
Hello! 

Everything looks incredible! I only spotted one minor issue with the footer on medium screen sizes. The search bar seems to be overlapping with the social media icons.

Otherwise it looks amazing! :)

<img width="598" alt="Screenshot 2019-04-16 11 53 30" src="https://user-images.githubusercontent.com/31852223/56225063-ae4c8500-603e-11e9-8085-314e5f906f15.png">

-Patricia

**Comment by nep2ne** [comment]
Thanks Patricia! I'll fix that. :)
