### ISSUE TITLE
Voice Over Product Details/Checkout

### ISSUE THREAD

**Issue by Sebby-T** [nep2ne/ecommerce-pattern-library#8]
Overall the voice over accessibility is pretty good for these pages.

The header and footer need aria labels descriptions so the user understands where they go.
Also, the search bar doesn't show when focused.

For the product details page, it reads all the information. That includes the 4 images of the notebook. But Otherwise, it reads the data just fine.

The Checkout form works great!

Your website looks beautiful! Good work

**Comment by nep2ne** [comment]
Thanks Seb! I'll fix that. :)
